# Generated by Django 4.2.1 on 2026-05-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_data', '0009_room_studioclosure_scheduledclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipMonthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('retained', 'Retained'), ('new', 'New'), ('reactivated', 'Reactivated'), ('not_renewed', 'Not Renewed')], db_index=True, max_length=20)),
                ('current_month_member', models.BooleanField(default=False)),
                ('previous_month_member', models.BooleanField(default=False)),
                ('membership_days', models.PositiveIntegerField(default=0)),
                ('previous_membership_days', models.PositiveIntegerField(default=0)),
                ('membership_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('studio_inference_method', models.CharField(choices=[('attendance_month', 'Attendance in Month'), ('recent_attendance', 'Recent Attendance'), ('previous_month', 'Previous Month'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('rebuilt_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_month_statuses', to='core_data.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_month_statuses', to='core_data.site')),
                ('source_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_month_statuses', to='core_data.servicepurchase')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_month_statuses', to='core_data.studio')),
            ],
            options={
                'ordering': ['-month', 'status', 'client__name'],
                'unique_together': {('site', 'month', 'client')},
            },
        ),
    ]
