# Generated by Django 4.2.1 on 2026-06-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_membershipmonthstatus_purchase_studio_method"),
        ("core_data", "0017_useraccessprofile_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientStudioMonthlyMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField(db_index=True)),
                ("total_bookings", models.PositiveIntegerField(default=0)),
                ("attended_visits", models.PositiveIntegerField(default=0)),
                ("no_shows", models.PositiveIntegerField(default=0)),
                ("late_cancels", models.PositiveIntegerField(default=0)),
                ("active_weeks", models.PositiveIntegerField(default=0)),
                ("active_week_starts", models.JSONField(blank=True, default=list)),
                ("attendance_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("service_purchase_count", models.PositiveIntegerField(default=0)),
                ("service_spending", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("membership_spending", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("non_membership_spending", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("general_sales_spending", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("first_visit_date", models.DateField(blank=True, null=True)),
                ("last_visit_date", models.DateField(blank=True, null=True)),
                ("first_purchase_date", models.DateField(blank=True, null=True)),
                ("last_purchase_date", models.DateField(blank=True, null=True)),
                ("active_membership_days", models.PositiveIntegerField(default=0)),
                ("active_membership_dates", models.JSONField(blank=True, default=list)),
                ("membership_status", models.CharField(blank=True, choices=[("retained", "Retained"), ("new", "New"), ("reactivated", "Reactivated"), ("not_renewed", "Not Renewed")], db_index=True, max_length=20, null=True)),
                ("rebuilt_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="studio_monthly_metrics", to="core_data.client")),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="client_studio_monthly_metrics", to="core_data.site")),
                ("studio", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="client_monthly_metrics", to="core_data.studio")),
            ],
            options={
                "ordering": ["-month", "site__name", "studio__name", "client__name"],
                "indexes": [
                    models.Index(fields=["site", "month"], name="analytics_c_site_id_a48886_idx"),
                    models.Index(fields=["studio", "month"], name="analytics_c_studio__4bfbdb_idx"),
                    models.Index(fields=["client", "month"], name="analytics_c_client__374092_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(studio__isnull=False), fields=("site", "studio", "client", "month"), name="unique_client_studio_month_metric"),
                    models.UniqueConstraint(condition=models.Q(studio__isnull=True), fields=("site", "client", "month"), name="unique_client_unassigned_month_metric"),
                ],
            },
        ),
    ]
