# Generated by Django 4.2.1 on 2026-06-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0017_useraccessprofile_language'),
        ('analytics', '0003_clientstudiomonthlymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStudioWeeklyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('attended_visits', models.PositiveIntegerField(default=0)),
                ('no_shows', models.PositiveIntegerField(default=0)),
                ('late_cancels', models.PositiveIntegerField(default=0)),
                ('attendance_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('active_membership_days', models.PositiveIntegerField(default=0)),
                ('active_membership_dates', models.JSONField(blank=True, default=list)),
                ('had_active_membership', models.BooleanField(default=False)),
                ('rebuilt_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_weekly_metrics', to='core_data.client')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_studio_weekly_metrics', to='core_data.site')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_weekly_metrics', to='core_data.studio')),
            ],
            options={
                'ordering': ['-week_start', 'site__name', 'studio__name', 'client__name'],
                'indexes': [models.Index(fields=['site', 'week_start'], name='analytics_c_site_id_3a86eb_idx'), models.Index(fields=['studio', 'week_start'], name='analytics_c_studio__c20716_idx'), models.Index(fields=['client', 'week_start'], name='analytics_c_client__66976e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='clientstudioweeklymetric',
            constraint=models.UniqueConstraint(condition=models.Q(('studio__isnull', False)), fields=('site', 'studio', 'client', 'week_start'), name='unique_client_studio_week_metric'),
        ),
        migrations.AddConstraint(
            model_name='clientstudioweeklymetric',
            constraint=models.UniqueConstraint(condition=models.Q(('studio__isnull', True)), fields=('site', 'client', 'week_start'), name='unique_client_unassigned_week_metric'),
        ),
    ]
