# Generated by Django 4.2.1 on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_clientstudioweeklymetric_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientstudiomonthlymetric",
            name="first_non_trial_purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientstudiomonthlymetric",
            name="tracked_purchase_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
