# Generated by Django 4.2.1 on 2026-05-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='classtype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='room',
            name='center',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Center',
        ),
        migrations.DeleteModel(
            name='ClassType',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
