# Generated by Django 4.2.1 on 2026-05-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0003_site_studio_staffmember_servicecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRawRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_payload', models.JSONField()),
                ('normalized_payload', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_raw_rows', to='core_data.reportimport')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_raw_rows', to='core_data.site')),
            ],
            options={
                'ordering': ['report_import_id', 'row_number'],
                'unique_together': {('report_import', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('current_row_hash', models.CharField(db_index=True, max_length=64)),
                ('visit_date', models.DateField()),
                ('visit_time_raw', models.CharField(max_length=50)),
                ('weekday_raw', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('remaining_visits', models.IntegerField(blank=True, null=True)),
                ('staff_paid', models.BooleanField(blank=True, null=True)),
                ('late_cancel', models.BooleanField(default=False)),
                ('no_show', models.BooleanField(default=False)),
                ('scheduling_method', models.CharField(blank=True, max_length=255, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_visits', to='core_data.client')),
                ('first_seen_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_attendance_visits', to='core_data.reportimport')),
                ('last_seen_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_attendance_visits', to='core_data.reportimport')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_visits', to='core_data.paymentmethod')),
                ('pricing_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_visits', to='core_data.pricingoption')),
                ('sale_studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_attendance_visits', to='core_data.studio')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_visits', to='core_data.servicecategory')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_visits', to='core_data.site')),
                ('source_raw_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_attendance_visits', to='core_data.attendancerawrow')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_visits', to='core_data.staffmember')),
                ('visit_studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_attendance_visits', to='core_data.studio')),
            ],
            options={
                'ordering': ['-visit_date', 'visit_time_raw', 'client__name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceVisitVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core_data.attendancevisit')),
                ('raw_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_versions', to='core_data.attendancerawrow')),
                ('report_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_versions', to='core_data.reportimport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
