# Generated by Django 4.2.1 on 2025-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0004_machine_updated_by_objective_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prop',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prop',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
