# Generated by Django 4.2.1 on 2026-05-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0004_attendancerawrow_attendancevisit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('current_row_hash', models.CharField(db_index=True, max_length=64)),
                ('sale_date', models.DateField()),
                ('sale_number', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('computation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_notes', models.TextField(blank=True, null=True)),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='core_data.client')),
                ('first_seen_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_sale_lines', to='core_data.reportimport')),
                ('last_seen_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_sale_lines', to='core_data.reportimport')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='core_data.paymentmethod')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_lines', to='core_data.site')),
            ],
            options={
                'ordering': ['-sale_date', 'sale_number', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('current_row_hash', models.CharField(db_index=True, max_length=64)),
                ('sale_date', models.DateField()),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('activation_offset_days', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_equivalent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('non_cash_equivalent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_purchases', to='core_data.client')),
                ('first_seen_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_service_purchases', to='core_data.reportimport')),
                ('last_seen_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_service_purchases', to='core_data.reportimport')),
                ('pricing_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_purchases', to='core_data.pricingoption')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_purchases', to='core_data.servicecategory')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_purchases', to='core_data.site')),
            ],
            options={
                'ordering': ['-sale_date', 'client__name', 'pricing_option__name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePurchaseRawRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_payload', models.JSONField()),
                ('normalized_payload', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_purchase_raw_rows', to='core_data.reportimport')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_purchase_raw_rows', to='core_data.site')),
            ],
            options={
                'ordering': ['report_import_id', 'row_number'],
                'unique_together': {('report_import', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='ServicePurchaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_purchase_versions', to='core_data.servicepurchaserawrow')),
                ('report_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_purchase_versions', to='core_data.reportimport')),
                ('service_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core_data.servicepurchase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='servicepurchase',
            name='source_raw_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_service_purchases', to='core_data.servicepurchaserawrow'),
        ),
        migrations.CreateModel(
            name='SaleRawRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_payload', models.JSONField()),
                ('normalized_payload', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_raw_rows', to='core_data.reportimport')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_raw_rows', to='core_data.site')),
            ],
            options={
                'ordering': ['report_import_id', 'row_number'],
                'unique_together': {('report_import', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='SaleLineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_line_versions', to='core_data.salerawrow')),
                ('report_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_line_versions', to='core_data.reportimport')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core_data.saleline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='saleline',
            name='source_raw_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sale_lines', to='core_data.salerawrow'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='core_data.studio'),
        ),
    ]
