# Generated by Django 5.1.6 on 2025-02-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0006_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='unilateral_bilateral',
            new_name='unilateral',
        ),
    ]
