# Generated by Django 4.2.1 on 2025-02-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0007_rename_unilateral_bilateral_exercise_unilateral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='box',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
