# Generated by Django 4.2.1 on 2026-05-13 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0007_seed_default_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('mindbody_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mindbody_name', models.CharField(blank=True, max_length=255, null=True)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('room_type', models.CharField(choices=[('group', 'Group'), ('private', 'Private'), ('mixed', 'Mixed')], default='group', max_length=20)),
                ('default_group_capacity', models.PositiveIntegerField(default=0)),
                ('default_private_capacity', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core_data.site')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core_data.studio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['site__name', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerAvailabilityRawRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_payload', models.JSONField()),
                ('normalized_payload', models.JSONField(default=dict)),
                ('is_class_row', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_availability_raw_rows', to='core_data.reportimport')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_availability_raw_rows', to='core_data.site')),
            ],
            options={
                'ordering': ['report_import_id', 'row_number'],
                'unique_together': {('report_import', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField()),
                ('class_name', models.CharField(max_length=255)),
                ('service_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('unavailable', 'Unavailable'), ('needs_review', 'Needs Review'), ('conflict', 'Conflict')], db_index=True, default='scheduled', max_length=30)),
                ('source', models.CharField(choices=[('trainer_availability', 'Trainer Availability'), ('manual', 'Manual')], default='manual', max_length=50)),
                ('natural_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('current_row_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('manually_modified', models.BooleanField(default=False)),
                ('review_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_classes', to='core_data.room')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='core_data.site')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='core_data.reportimport')),
                ('source_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='core_data.traineravailabilityrawrow')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='core_data.staffmember')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_classes', to='core_data.studio')),
            ],
            options={
                'ordering': ['class_date', 'start_time', 'studio__name', 'room__name', 'staff_member__name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceClassMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_method', models.CharField(choices=[('exact_instructor_time', 'Exact Instructor Time'), ('single_class_same_time', 'Single Class Same Time'), ('manual', 'Manual'), ('ambiguous', 'Ambiguous'), ('unmatched', 'Unmatched')], db_index=True, max_length=40)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('candidate_class_ids', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(auto_now=True)),
                ('attendance_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_match', to='core_data.attendancevisit')),
                ('scheduled_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_matches', to='core_data.scheduledclass')),
            ],
            options={
                'ordering': ['attendance_visit__visit_date', 'attendance_visit__visit_time_raw'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['site', 'class_date', 'start_time'], name='core_data_s_site_id_90eb48_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['site', 'studio', 'class_date', 'start_time'], name='core_data_s_site_id_51597a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['site', 'room', 'class_date', 'start_time'], name='core_data_s_site_id_4c9a2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('site', 'studio', 'normalized_name')},
        ),
    ]
