# Generated by Django 4.2.1 on 2026-05-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0007_seed_default_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingoption',
            name='track_retention',
            field=models.BooleanField(default=False),
        ),
    ]
