# Generated by Django 4.2.1 on 2025-02-28 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0008_alter_exercise_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('spring_type', models.CharField(choices=[('car', 'Carriage'), ('tower', 'Tower')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSpringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spring_configurations', to='core_data.exercise')),
                ('spring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_data.spring')),
            ],
            options={
                'unique_together': {('exercise', 'spring')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='springs',
            field=models.ManyToManyField(through='core_data.ExerciseSpringConfig', to='core_data.spring'),
        ),
    ]
