# Generated by Django 4.2.1 on 2026-05-11 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0008_pricingoption_track_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('mindbody_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mindbody_name', models.CharField(blank=True, max_length=255, null=True)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('room_type', models.CharField(choices=[('group', 'Group'), ('private', 'Private'), ('mixed', 'Mixed')], default='group', max_length=20)),
                ('group_capacity', models.PositiveIntegerField(default=0)),
                ('private_capacity', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core_data.site')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core_data.studio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['site__name', 'name'],
                'abstract': False,
                'unique_together': {('site', 'studio', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudioClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closure_date', models.DateField()),
                ('all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_closures', to='core_data.room')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_closures', to='core_data.site')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_closures', to='core_data.studio')),
            ],
            options={
                'ordering': ['closure_date', 'start_time', 'site__name', 'studio__name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('class_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('group', 'Group'), ('private', 'Private')], default='group', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('unavailable', 'Unavailable')], default='scheduled', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='core_data.pricingoption')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='core_data.room')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='core_data.site')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='core_data.staffmember')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='core_data.studio')),
            ],
            options={
                'ordering': ['class_date', 'start_time', 'studio__name', 'room__name'],
            },
        ),
    ]
