# Generated by Django 4.2.1 on 2025-02-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0009_spring_exercisespringconfig_exercise_springs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spring',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='spring',
            unique_together={('spring_type', 'name')},
        ),
    ]
