# Generated by Codex on 2026-05-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_data", "0009_room_studioclosure_scheduledclass"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("site", "studio", "normalized_name")},
        ),
        migrations.CreateModel(
            name="TrainerAvailabilityRawRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("row_number", models.PositiveIntegerField()),
                ("row_hash", models.CharField(db_index=True, max_length=64)),
                ("raw_payload", models.JSONField()),
                ("normalized_payload", models.JSONField(default=dict)),
                ("is_class_row", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_availability_raw_rows",
                        to="core_data.reportimport",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_availability_raw_rows",
                        to="core_data.site",
                    ),
                ),
            ],
            options={
                "ordering": ["report_import_id", "row_number"],
                "unique_together": {("report_import", "row_number")},
            },
        ),
        migrations.AlterField(
            model_name="scheduledclass",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheduled_classes",
                to="core_data.room",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledclass",
            name="studio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheduled_classes",
                to="core_data.studio",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledclass",
            name="class_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="scheduledclass",
            name="start_time",
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="scheduledclass",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("cancelled", "Cancelled"),
                    ("unavailable", "Unavailable"),
                    ("needs_review", "Needs Review"),
                    ("conflict", "Conflict"),
                ],
                db_index=True,
                default="scheduled",
                max_length=30,
            ),
        ),
        migrations.AlterModelOptions(
            name="scheduledclass",
            options={"ordering": ["class_date", "start_time", "studio__name", "room__name", "staff_member__name"]},
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="source",
            field=models.CharField(
                choices=[("trainer_availability", "Trainer Availability"), ("manual", "Manual")],
                default="manual",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="source_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_classes",
                to="core_data.reportimport",
            ),
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="source_row",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_classes",
                to="core_data.traineravailabilityrawrow",
            ),
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="natural_key",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="current_row_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="manually_modified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scheduledclass",
            name="review_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="AttendanceClassMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("exact_instructor_time", "Exact Instructor Time"),
                            ("single_class_same_time", "Single Class Same Time"),
                            ("manual", "Manual"),
                            ("ambiguous", "Ambiguous"),
                            ("unmatched", "Unmatched"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("confidence", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("candidate_class_ids", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                ("matched_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_match",
                        to="core_data.attendancevisit",
                    ),
                ),
                (
                    "scheduled_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_matches",
                        to="core_data.scheduledclass",
                    ),
                ),
            ],
            options={
                "ordering": ["attendance_visit__visit_date", "attendance_visit__visit_time_raw"],
            },
        ),
        migrations.AddIndex(
            model_name="scheduledclass",
            index=models.Index(fields=["site", "class_date", "start_time"], name="core_data_s_site_id_90eb48_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledclass",
            index=models.Index(
                fields=["site", "studio", "class_date", "start_time"],
                name="core_data_s_site_id_51597a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledclass",
            index=models.Index(fields=["site", "room", "class_date", "start_time"], name="core_data_s_site_id_4c9a2b_idx"),
        ),
    ]
