# Generated by Django 4.2.1 on 2026-05-15 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0010_trainer_availability_schedule_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRoomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pilates', max_length=150)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('active_from', models.DateField()),
                ('active_until', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_templates', to='core_data.room')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_room_templates', to='core_data.site')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_room_templates', to='core_data.staffmember')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_room_templates', to='core_data.studio')),
            ],
            options={
                'ordering': ['studio__name', 'room__name', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExpectedClassSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField()),
                ('name', models.CharField(default='Pilates', max_length=150)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('missing', 'Missing'), ('cancelled', 'Cancelled'), ('unavailable', 'Unavailable'), ('manually_created', 'Manually Created'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=30)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_class_slots', to='core_data.room')),
                ('scheduled_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_slots', to='core_data.scheduledclass')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_class_slots', to='core_data.site')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_class_slots', to='core_data.staffmember')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_class_slots', to='core_data.studio')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_slots', to='core_data.weeklyroomtemplate')),
            ],
            options={
                'ordering': ['slot_date', 'start_time', 'studio__name', 'room__name'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklyroomtemplate',
            index=models.Index(fields=['site', 'studio', 'room', 'weekday', 'start_time'], name='core_data_w_site_id_96fe46_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyroomtemplate',
            index=models.Index(fields=['active_from', 'active_until'], name='core_data_w_active__284c27_idx'),
        ),
        migrations.AddIndex(
            model_name='expectedclassslot',
            index=models.Index(fields=['site', 'studio', 'slot_date', 'start_time'], name='core_data_e_site_id_511a26_idx'),
        ),
        migrations.AddIndex(
            model_name='expectedclassslot',
            index=models.Index(fields=['site', 'room', 'slot_date', 'start_time'], name='core_data_e_site_id_2608cb_idx'),
        ),
        migrations.AddIndex(
            model_name='expectedclassslot',
            index=models.Index(fields=['status'], name='core_data_e_status_2809a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expectedclassslot',
            unique_together={('site', 'room', 'slot_date', 'start_time', 'end_time')},
        ),
    ]
