# Generated by Django 4.2.1 on 2026-05-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0011_weeklyroomtemplate_expectedclassslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportimport',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_imports', to='core_data.studio'),
        ),
        migrations.AddField(
            model_name='servicepurchase',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_purchases', to='core_data.studio'),
        ),
        migrations.AddField(
            model_name='servicepurchaserawrow',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_purchase_raw_rows', to='core_data.studio'),
        ),
    ]
