# Generated by Django 4.2.1 on 2025-03-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0011_routine_routineexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='number_exercises',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routine',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
