# Generated by Django 5.1.6 on 2025-03-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0012_routine_active_routine_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercise',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
