# Generated by Django 4.2.1 on 2026-05-18 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0012_reportimport_studio_servicepurchase_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='expected_from_template',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='reconciliation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='schedule_status',
            field=models.CharField(choices=[('unreconciled', 'Unreconciled'), ('matched', 'Matched'), ('missing_from_report', 'Missing From Report'), ('unexpected_from_report', 'Unexpected From Report'), ('manual', 'Manual')], db_index=True, default='unreconciled', max_length=40),
        ),
        migrations.AddField(
            model_name='scheduledclass',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to='core_data.weeklyroomtemplate'),
        ),
        migrations.AlterField(
            model_name='scheduledclass',
            name='source',
            field=models.CharField(choices=[('trainer_availability', 'Trainer Availability'), ('expected_template', 'Expected Template'), ('manual', 'Manual')], default='manual', max_length=50),
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['site', 'schedule_status', 'class_date'], name='core_data_s_site_id_9a37a9_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledclass',
            index=models.Index(fields=['template', 'class_date'], name='core_data_s_templat_1258cd_idx'),
        ),
    ]
