# Generated by Django 4.2.1 on 2026-05-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0013_scheduledclass_expected_from_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingoption',
            name='is_trial_class',
            field=models.BooleanField(default=False),
        ),
    ]
