# Generated by Django 5.1.6 on 2025-03-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0013_routineexercise_comment_alter_routineexercise_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='number_exercises',
        ),
    ]
