# Generated by Django 5.1.6 on 2025-03-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0014_remove_routine_number_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='objective',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routine',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
