# Generated by Django 4.2.1 on 2026-05-20 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core_data', '0014_pricingoption_is_trial_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_money', models.BooleanField(default=False)),
                ('can_upload_data', models.BooleanField(default=False)),
                ('can_edit_data', models.BooleanField(default=False)),
                ('can_reset_data', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_admin_logs', models.BooleanField(default=False)),
                ('allowed_sites', models.ManyToManyField(blank=True, related_name='allowed_user_profiles', to='core_data.site')),
                ('allowed_studios', models.ManyToManyField(blank=True, related_name='allowed_user_profiles', to='core_data.studio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_money', models.BooleanField(default=False)),
                ('can_upload_data', models.BooleanField(default=False)),
                ('can_edit_data', models.BooleanField(default=False)),
                ('can_reset_data', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_admin_logs', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to='auth.group')),
            ],
        ),
    ]
