# Generated by Django 5.1.6 on 2025-03-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0015_alter_exercise_name_alter_machine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='objective',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='prop',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='routine',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
