# Generated by Django 4.2.1 on 2026-05-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0016_create_default_access_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccessprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2),
        ),
    ]
