# Generated by Django 4.2.1 on 2026-07-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0017_useraccessprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancevisit',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='attendancevisit',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancevisit',
            name='removed_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancevisit',
            name='removed_seen_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_attendance_visits', to='core_data.reportimport'),
        ),
        migrations.AddField(
            model_name='reportimport',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='reportimport',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportimport',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
