# Generated by Django 4.2.1 on 2025-05-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0018_center_tag_exercise_tags_routine_tags_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='machine',
        ),
        migrations.AddField(
            model_name='routine',
            name='machines',
            field=models.ManyToManyField(related_name='routines', to='core_data.machine'),
        ),
    ]
