# Generated by Django 4.2.1 on 2025-05-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0020_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='RoutineSession',
        ),
    ]
