# Generated by Django 4.2.1 on 2025-07-06 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0021_rename_session_routinesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routinesessions', to='core_data.room'),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routinesessions', to='core_data.routine'),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routinesessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
