# Generated by Django 4.2.1 on 2025-07-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0022_tag_image_alter_routinesession_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinesession',
            name='state',
            field=models.IntegerField(choices=[(0, 'Programada'), (1, 'En progreso'), (2, 'Completada'), (-1, 'Cancelada')], default=0),
        ),
        migrations.AddField(
            model_name='routinesession',
            name='userFeedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
