# Generated by Django 4.2.1 on 2025-07-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0023_routinesession_state_routinesession_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='machine',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='objective',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='prop',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='routine',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
    ]
