# Generated by Django 4.2.1 on 2025-08-05 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0024_alter_center_slug_alter_exercise_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineSessionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='core_data.exercise')),
                ('routine_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core_data.routinesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_session_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Routine Session Log',
                'verbose_name_plural': 'Routine Session Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
