# Generated by Django 4.2.1 on 2026-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0025_routinesessionlog'),
    ]

    operations = [
        # Cambios genéricos: Ampliar campos name y slug en múltiples modelos
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='center',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='machine',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='objective',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='objective',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='prop',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='prop',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='routine',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='routinesession',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='routinesessions', to='core_data.routine'),
        ),
    ]
