# Generated by Django 4.2.1 on 2026-03-02 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0026_alter_name_slug_fields'),
    ]

    operations = [
        # Crear modelo SessionSeries (solo semanal, sin frequency ni day_of_month)
        migrations.CreateModel(
            name='SessionSeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo de la serie', max_length=200)),
                ('weekdays', models.JSONField(help_text='Lista de días de la semana [0-6] para recurrencia semanal')),
                ('start_date', models.DateField(help_text='Fecha de inicio de la serie')),
                ('end_date', models.DateField(help_text='Fecha de fin de la serie')),
                ('time', models.TimeField(help_text='Hora a la que se programan las sesiones')),
                ('duration', models.IntegerField(default=60, help_text='Duración de cada sesión en minutos')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_session_series', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_series', to='core_data.room')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_series', to='core_data.routine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_session_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Series',
                'verbose_name_plural': 'Session Series',
                'ordering': ['-created_at'],
            },
        ),
        
        # Añadir campos a RoutineSession
        migrations.AddField(
            model_name='routinesession',
            name='name',
            field=models.CharField(max_length=200, blank=True, null=True, help_text='Nombre descriptivo de la sesión'),
        ),
        migrations.AddField(
            model_name='routinesession',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duración de la sesión en minutos'),
        ),
        migrations.AddField(
            model_name='routinesession',
            name='session_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_sessions', to='core_data.sessionseries'),
        ),
    ]
