# Generated by Django 4.2.1 on 2026-03-11 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0027_sessionseries_and_session_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('login_type', models.CharField(choices=[('main', 'Login Principal'), ('sub', 'Sublogin')], default='main', help_text='Tipo de login: principal o sublogin', max_length=10)),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/dispositivo', null=True)),
                ('success', models.BooleanField(default=True, help_text='Si el login fue exitoso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
