# Generated by Django 4.2.1 on 2026-04-18 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_data", "0028_create_login_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRoutineAssignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(help_text="Fecha a la que aplica la asignación diaria")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_routine_assignments",
                        to="core_data.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_routine_assignment_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_routine_assignments",
                        to="core_data.room",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_assignments",
                        to="core_data.routine",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_routine_assignment_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Routine Assignment",
                "verbose_name_plural": "Daily Routine Assignments",
                "ordering": ["date", "center__name", "room__name"],
                "unique_together": {("date", "room")},
            },
        ),
        migrations.AddField(
            model_name="routinesession",
            name="daily_routine_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignación diaria que pobló originalmente la rutina de esta sesión",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_sessions",
                to="core_data.dailyroutineassignment",
            ),
        ),
        migrations.AddField(
            model_name="routinesession",
            name="routine_manually_overridden",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la rutina fue modificada manualmente después de una asignación diaria",
            ),
        ),
    ]
