# Generated by Django 4.2.1 on 2026-04-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0029_dailyroutineassignment_routinesession_assignment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='login_type',
            field=models.CharField(choices=[('main', 'Login Principal'), ('secondary', 'Login Secundario'), ('logout', 'Cierre de Sesión')], default='main', help_text='Tipo de login: principal o sublogin', max_length=10),
        ),
    ]
