# Generated by Django 4.2.1 on 2026-04-19 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_data", "0030_alter_loginlog_login_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralRoutineAssignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(help_text="Fecha de la planificación general", unique=True)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="general_routine_assignment_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_assignments",
                        to="core_data.routine",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="general_routine_assignment_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "General Routine Assignment",
                "verbose_name_plural": "General Routine Assignments",
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="dailyroutineassignment",
            name="general_routine_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignación general de la que deriva esta asignación de sala",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_assignments",
                to="core_data.generalroutineassignment",
            ),
        ),
        migrations.AddField(
            model_name="dailyroutineassignment",
            name="overrides_general_assignment",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la asignación de sala difiere de la asignación general del día",
            ),
        ),
    ]
